---

################################
# Install the keepalived package

- name: Install package keepalived
  ansible.builtin.package:
    name: keepalived
    state: "{{ keepalived.package.state }}"

######################################
# Create the script group, if necessary

- name: Create keepalived script group, {{ keepalived.script.group }}
  ansible.builtin.group:
    name: "{{ keepalived.script.group }}"
    state: present

######################################
# Create the script user, if necessary

- name: Create keepalived script user, {{ keepalived.script.user }}
  when: keepalived.script.user != 'root'
  ansible.builtin.user:
    name: "{{ keepalived.script.user }}"
    group: "{{ keepalived.script.group }}"
    comment: "User to run keepalived scripts"
    home: "{{ keepalived.dir.run }}"
    shell: "{{ keepalived.script.login }}"
    append: false
    create_home: true
    system: true

##################################
# Install/Update the configuration

- name: Create keepalived etc directory, {{ keepalived.dir.etc }}
  ansible.builtin.file:
    path: "{{ keepalived.dir.etc }}"
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=,o="

- name: Create other keepalived directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ keepalived.script.user }}"
    group: "{{ keepalived.script.group }}"
    mode: "u=rwx,g=,o="
  loop:
    - "{{ keepalived.dir.lib }}"
    - "{{ keepalived.dir.run }}"
    - "{{ keepalived.dir.tmp }}"

- name: Create keepalived configuration, {{ path }}
  vars:
    path: "{{ keepalived.dir.etc }}/{{ keepalived.config.file }}"
  ansible.builtin.template:
    src: "keepalived.conf.j2"
    dest: "{{ path }}"
    owner: root
    group: root
    mode: "u=r,g=,o="

- name: Create keepalived k3s check script, {{ path }}
  vars:
    path: "{{ keepalived.dir.lib }}/{{ keepalived.script.name }}"
  ansible.builtin.template:
    src: "keepalived_check_k3s.sh.j2"
    dest: "{{ path }}"
    owner: "{{ keepalived.script.user }}"
    group: "{{ keepalived.script.group }}"
    mode: "u=rwx,g=rx,o=rx"

# You have to stat first because touch will ALWAYS change an existing file
- name: Check for the keepalived k3s script output file, {{ path }}
  vars:
    path: "{{ keepalived.dir.run }}/{{ keepalived.script.output }}"
  ansible.builtin.stat:
    path: "{{ path }}"
  register: check_output

# We have to create the output file so that the script has permissions
- name: Create keepalived k3s script output file, {{ path }}
  vars:
    path: "{{ keepalived.dir.run }}/{{ keepalived.script.output }}"
  ansible.builtin.file:
    path: "{{ path }}"
    state: touch
    owner: "{{ keepalived.script.user }}"
    group: "{{ keepalived.script.group }}"
    mode: "u=rw,g=r,o=r"
  when: not check_output.stat.exists

- name: Copy the keepalived kubeconfig, {{ str }}
  vars:
    src: "{{ keepalived.config.k3s }}"
    dest: "{{ keepalived.dir.lib }}/{{ keepalived.script.kubeconfig }}"
    str: "{{ src }} --> {{ dest }}"
  ansible.builtin.copy:
    remote_src: true
    src: "{{ src }}"
    dest: "{{ dest }}"
    owner: "{{ keepalived.script.user }}"
    group: "{{ keepalived.script.group }}"
    mode: "u=r,g=,o="

#####################################
# Ensure non-local binding is enabled

- name: Ensure ipv4 nonlocal binding is enabled
  ansible.posix.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: "1"
    state: present
    reload: true

- name: Ensure ipv6 nonlocal binding is enabled
  ansible.posix.sysctl:
    name: net.ipv6.ip_nonlocal_bind
    value: "1"
    state: present
    reload: true

###################
# Start the service

- name: Start keepalived service
  register: check_started
  ansible.builtin.service:
    name: keepalived
    enabled: true
    state: started

##############################################
# TODO: need tasks to label and annotate nodes

