---
- name: Enable cgroup support if not already enabled
  ansible.builtin.lineinfile:
    path: /boot/boot.txt
    backrefs: true
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  register: cgroup_support

- name: Regenerate bootloader image
  ansible.builtin.shell: ./mkscr
  args:
    chdir: /boot
  notify: Reboot Pi
  when: cgroup_support.changed
