---
# These variables are not meant to be changed.
# All changes should happen in "inventory.yml".
#
# TODO: clean up these variables -- perhaps, with dictionaries.
#
k3s_version: "{{ install_k3s_version | default('undefined') }}"
k3s_commit: "{{ install_k3s_commit | default('undefined') }}"

k3s_channel_url: "{{ install_k3s_channel_url | default('https://update.k3s.io/v1-release/channels') }}"
k3s_channel: "{{ install_k3s_channel | default('stable') }}"

extra_server_args: "{{ install_server_args | default('') }}"
extra_agent_args: "{{ install_agent_args | default('') }}"

extra_server_manifests: "{{ install_additional_server_manifests | default([]) }}"
extra_agent_manifests: "{{ install_additional_agent_manifests | default([]) }}"
extra_server_packages: "{{ install_additional_server_packages | default([]) }}"
extra_agent_packages: "{{ install_additional_agent_packages | default([]) }}"

# Added so that we can check when the default is not being used
default_systemd_dir: '/etc/systemd/system'
default_bin_dir: '/usr/local/bin'
default_data_dir: '/var/lib/rancher/k3s'

systemd_dir: "{{ install_k3s_systemd_dir | default(default_systemd_dir) }}"
bin_dir: "{{ install_k3s_bin_dir | default(default_bin_dir) }}"
data_dir: "{{ install_k3s_data_dir | default(default_data_dir) }}"

first_server: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
api_endpoint: "{{ (ha_cluster_vip | mandatory) if (ha_enabled | default(false)) else first_server }}"
api_port: "{{ cluster_port | default('6443') }}"

k3s_cluster_config: "{{ cluster_config | default('cluster.conf') }}"
k3s_cluster_method: "{{ ha_cluster_method | default('keepalived') }}"

k3s_token: "{{ ha_k3s_token | default('MySuperSecureToken') }}"

# Services information
k3s_services:
  - k3s
  - k3s-agent

k3s_service_file_extensions:
  - service
  - service.env

# Supported HA Cluster Methods
k3s_cluster_methods:
  - external
  - kube-vip
  - keepalived

