---
# These variables are not meant to be changed.
# All changes should happen in "inventory.yml".
#
# install_* variables match INSTALL_* variables in k3s-install.sh.
# extra_* variables are used to supplement arguments to the k3s executable,
# provide additional manifests, and/or have additional packages installed.
#
# install_* and extra_* variables should be set in "inventory.yml".
#

######################################################################
# k3s-ansible default values
# Added so that we can check when the default is not being used
#
defaults:
  channel:
    tag: 'stable'
    url: 'https://update.k3s.io/v1-release/channels'
  dir:
    systemd: '/etc/systemd/system'
    bin: '/usr/local/bin'
    data: '/var/lib/rancher/k3s'
    etc: '/etc/rancher/k3s'
  config:  # There are always basenames, never paths
    userdir: '.kube'  # The directory to be created in ~{{ ansible_user }}
    system: 'k3s.yaml'  # The name of the system config in {{ k3s.dir.etc }}
    local: 'config-local'  # The kubeconfig using localhost
    cluster: 'config-cluster'  # The kubeconfig using {{ k3s.cluster.address }}
  cluster:
    first: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
    method: 'keepalived'
    token: 'MySuperSecureToken'
    port: '6443'
  memory:
    high: '1G'
    max: '2G'
    swapmax: '1G'

######################################################################
# k3s-ansible reference values
#
reference:
  service:  # systemd unit information
    names:
      - 'k3s'
      - 'k3s-agent'
    extensions:
      - 'service'
      - 'service.env'
  cluster:
    methods:
      - 'external'
      - 'kube-vip'
      - 'keepalived'
    roles:
      external: ''
      kube-vip: 'ha_kube_vip'
      keepalived: 'ha_keepalived'

######################################################################
# k3s-ansible configuration variables
#
k3s:
  version:
    tag: "{{ install_k3s_version | default('undefined') }}"
    commit: "{{ install_k3s_commit | default('undefined') }}"

  channel:
    tag: "{{ install_k3s_channel | default(defaults.channel.tag) }}"
    url: "{{ install_k3s_channel_url | default(defaults.channel.url) }}"

  dir:
    systemd: "{{ install_k3s_systemd_dir | default(defaults.dir.systemd) }}"
    bin: "{{ install_k3s_bin_dir | default(defaults.dir.bin) }}"
    # NOTE: k3s-install.sh does not support changing the data/ or etc/ directories
    data: "{{ install_k3s_data_dir | default(defaults.dir.data) }}"
    etc: "{{ install_k3s_etc_dir | default(defaults.dir.etc) }}"

  args:
    # These are used instead of INSTALL_K3S_EXEC
    server: "{{ extra_server_args | default('') }}"
    agent: "{{ extra_agent_args | default('') }}"

  manifests:
    server: "{{ extra_server_manifests | default([]) }}"
    agent: "{{ extra_agent_manifests | default([]) }}"

  packages:
    server: "{{ extra_server_packages | default([]) }}"
    agent: "{{ extra_agent_packages | default([]) }}"

  config:
    # k3s_config variables are always basenames, relative to the directories in which they are put
    userdir: "{{ kube_dir | default(defaults.config.userdir) | basename }}"
    system: "{{ system_config | default(defaults.config.system) | basename }}"
    local: "{{ local_config | default(defaults.config.local) | basename }}"
    cluster: "{{ cluster_config | default(defaults.config.cluster) | basename }}"

  cluster:
    method: "{{ ha_cluster_method | default(defaults.cluster.method) }}"
    token: "{{ ha_k3s_token | default(defaults.cluster.token) }}"
    address: "{{ (ha_cluster_vip | mandatory) if (ha_enabled | default(false)) else defaults.cluster.first }}"
    port: "{{ cluster_port | default(defaults.cluster.port) }}"

  memory:
    high: "{{ service_memory_high | default(defaults.memory.high) }}"
    max: "{{ service_memory_max | default(defaults.memory.max) }}"
    swapmax: "{{ service_memory_swapmax | default(defaults.memory.swapmax) }}"
