---

# TODO: How do we use the node-token of defaults.cluster.endpoint instead of k3s.cluster.token?

tmp_args: >-
  {% if ansible_host == defaults.cluster.endpoint %}
    --cluster-init
    --tls-san {{ k3s.cluster.endpoint }}
  {% else %}
    --server https://{{ defaults.cluster.endpoint }}:{{ k3s.cluster.port }}
  {% endif %}
  --token {{ k3s.cluster.token }}
  {{ k3s.args.server | default('') }}

server_init_args: "{{ tmp_args | split('\n') | join }}"

