---

- name: Replace https://localhost:{{ api_port }} with https://{{ api_endpoint }}:{{ api_port }}
  lineinfile:
    path: "{{ k3s_cluster_config }}.tmp"
    regexp: '^(.*)https://.*:{{ api_port }}(.*)$'
    line: '\g<1>https://{{ api_endpoint }}:{{ api_port }}\g<2>'
    backrefs: yes
  changed_when: false

# The transfer uses a temporary/intermediate file because a fetched file is always "changed".
- name: Update cluster config, {{ k3s_cluster_config }}
  copy:
    src: "{{ k3s_cluster_config }}.tmp"
    dest: "{{ k3s_cluster_config }}"

- name: Remove temporary cluster config
  file:
    path: "{{ k3s_cluster_config }}.tmp"
    state: absent
  changed_when: false

- name: Wait for control-plane at {{ api_endpoint }}:{{ api_port }}
  wait_for:
    host: "{{ api_endpoint }}"
    port: "{{ api_port }}"
    timeout: 60

