---

# This file is used to configure the keepalived configuration files.  It typically does
# not need to be changed but you can at your discretion to suit your environment.
# These variables are used only when HA is enabled and the method chosen is keepalived.

keepalived:
  dir:
    etc: '/etc/keepalived'
    lib: '/var/lib/keepalived'
    run: '/var/run/keepalived'
    tmp: '/var/tmp'

  config:
    k3s: '{{ k3s.dir.etc }}/{{ k3s.config.system }}'
    file: "{{ 'keepalived.conf' | basename }}"

  script:
    name: 'keepalived_check_k3s.sh'
    output: 'k3s_check.out'
    kubeconfig: 'kubeconfig'
    user: 'keepalived'
    group: 'nogroup'
    login: '/usr/sbin/nologin'

  package:
    state: 'latest'
    remove: "{{ remove_packages | default(true) | bool }}"

  check:
    interval: 2
    timeout: 5
    rise: 3
    fall: 3

  option:
    instance_name: 'K3S_VI_1'
    interface: "{{ ansible_default_ipv4.interface }}"
    vr_id: 51
    priority:
      master: 11
      backup: 10
    advertisement_interval: 1
    network_mask: "{{ ha_cluster_subnet_mask | default('24') }}"
    password: 'MySuperSecretVRRPPassword'

