---

- name: Remove optional config file
  when: config_yaml is defined
  ansible.builtin.file:
    path: "/etc/rancher/k3s/config.yaml"
    state: absent

- name: Remove downloaded k3s binary
  ansible.builtin.file:
    path: "{{ k3s.dir.bin }}/k3s"
    state: absent
  when: remove_packages | bool

- name: Remove link to alternative K3s directory
  when: k3s.dir.data != defaults.dir.data
  ansible.builtin.file:
    path: "{{ defaults.dir.data }}"
    state: absent

#
# TODO: Where is k3s-selinux getting downloaded?
#       Are these tasks even necessary?
#
- name: Remove package k3s-selinux
  ansible.builtin.package:
    name: k3s-selinux
    state: absent
  when: remove_packages | bool

- name: Remove additional server packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ extra_server_packages | default([]) }}"
  when:
    - inventory_hostname in groups['server']
    - remove_packages | bool

- name: Remove additional agent packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ extra_agent_packages | default([]) }}"
  when:
    - inventory_hostname in groups['agent']
    - remove_packages | bool

- name: Remove yum repo files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/etc/yum.repos.d/rancher-k3s-common*.repo"
  when:
    - ansible_pkg_mgr == "yum"
    - remove_packages | bool

- name: Remove zypper repo files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/etc/zypp/repos.d/rancher-k3s-common*.repo"
  when:
    - ansible_pkg_mgr == "zypper"
    - remove_packages | bool

