---

- name: Include vars
  ansible.builtin.include_vars: "../roles/ha_kube-vip/defaults/main.yml"

#################################################
# Remove kube-vip
# TODO: Learn how to do this with kubernetes.core

- name: Remove kube-vip resource and files
  vars:
    path: "{{ data_dir }}/server/manifests/{{ k3s_cluster_method }}"
  block:
    - name: Check for the manifest directory, {{ path }}
      register: manifest_dir
      ansible.builtin.stat:
        path: "{{ path }}/."  # Use /. just in case it is a symlink

    - name: Remove kube-vip resources found in {{ path }}
      register: resources
      ansible.builtin.command: "{{ bin_dir }}/kubectl delete -R -f {{ path }}"
      run_once: true
      failed_when: false
      when:
        - manifest_dir.stat.isdir is defined
        - manifest_dir.stat.isdir

    - name: Remove manifest directory, {{ path }}
      register: files
      ansible.builtin.file:
        path: "{{ path }}"
        state: absent

####################################
# Remove cluster VIP from interface
# kube-vip does not do this for you.

- name: Remove {{ kube_vip_address }}{{ kube_vip_subnet }} from {{ kube_vip_interface }}
  ansible.builtin.command: "ip address delete {{ kube_vip_address }}{{ kube_vip_subnet }} dev {{ kube_vip_interface }}"
  register: ipaddr_delete
  when: kube_vip_address in (ansible_all_ipv4_addresses | list)
  failed_when: false # TODO: Sometimes the address disappears before we get to it?  Perhaps, kube-vip does delete this now.

###############################################
# Recommended in https://kube-vip.io/usage/k3s/
# See "Clean Environment".

- name: Reset local interface
  ansible.builtin.command: "{{ item }}"
  with_items:
    - ip addr flush dev lo
    - ip addr add 127.0.0.1/8 dev lo
  failed_when: false
  changed_when: false

