---

- name: Include vars
  ansible.builtin.include_vars: "../roles/{{ reference.cluster.roles[k3s.cluster.method] }}/defaults/main.yml"

###################
# Stop the service

- name: Stop keepalived service
  ansible.builtin.service:
    name: keepalived
    enabled: false
    state: stopped

##################################
# Delete the configuration

- name: Delete the keepalived configuration
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ keepalived.dir.etc }}"
    - "{{ keepalived.dir.lib }}"
    - "{{ keepalived.dir.tmp }}/{{ keepalived.script.output }}"
#   - "{{ keepalived.dir.etc }}/{{ keepalived.config.file }}"
#   - "{{ keepalived.dir.lib }}/{{ keepalived.script.name }}"
#   - "{{ keepalived.dir.lib }}/{{ keepalived.script.kubeconfig }}"

- name: Remove keepalived script user, {{ keepalived.script.user }}
  ansible.builtin.user:
    name: "{{ keepalived.script.user }}"
    state: absent
    remove: true
    force: true

##################################
# Uninstall the keepalived package

- name: Uninstall package keepalived
  ansible.builtin.package:
    name: keepalived
    state: absent
  when: keepalived.package.remove | bool

