---

- name: Include vars
  ansible.builtin.include_vars: "../roles/ha_keepalived/defaults/main.yml"

###################
# Stop the service

- name: Stop keepalived service
  ansible.builtin.service:
    name: keepalived
    enabled: false
    state: stopped

##################################
# Delete the configuration

- name: Delete the keepalived configuration
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ keepalived_etc_dir }}"
    - "{{ keepalived_lib_dir }}"
    - "{{ keepalived_run_dir }}/{{ keepalived_script_output }}"
#   - "{{ keepalived_etc_dir }}/{{ keepalived_config_file }}"
#   - "{{ keepalived_lib_dir }}/{{ keepalived_script_name }}"
#   - "{{ keepalived_lib_dir }}/{{ keepalived_script_kubeconfig }}"

- name: Remove keepalived script user, {{ keepalived_script_user }}
  ansible.builtin.user:
    name: "{{ keepalived_script_user }}"
    state: absent
    remove: true
    force: true

##################################
# Uninstall the keepalived package

- name: Uninstall package keepalived
  ansible.builtin.package:
    name: keepalived
    state: absent
  when: keepalived_package_remove | bool

