---

- name: Include vars
  ansible.builtin.include_vars: "../roles/{{ reference.cluster.roles[k3s.cluster.method] }}/defaults/main.yml"

###################
# Stop the service

- name: Stop keepalived service
  ansible.builtin.service:
    name: keepalived
    enabled: false
    state: stopped

##################################
# Delete the configuration

- name: Delete the keepalived directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ keepalived.dir.etc }}"
    - "{{ keepalived.dir.lib }}"
    - "{{ keepalived.dir.run }}"
    - "{{ keepalived.dir.tmp }}"

- name: Remove keepalived script user, {{ keepalived.script.user }}
  when: keepalived.script.user != "root"  # I learned the hard way. :-|
  ansible.builtin.user:
    name: "{{ keepalived.script.user }}"
    state: absent

- name: Remove keepalived script group, {{ keepalived.script.group }}
  when: keepalived.script.group != "root"
  ansible.builtin.group:
    name: "{{ keepalived.script.group }}"
    state: absent

##################################
# Uninstall the keepalived package

- name: Uninstall package keepalived
  ansible.builtin.package:
    name: keepalived
    state: absent
  when: keepalived.package.remove | bool

