---
################################################################################
# Create ctl commands
#

- name: Copy k3s.sh for symlink'd commands
  register: k3s_symlink
  ansible.builtin.template:
    src: "k3s.sh.j2"
    dest: "{{ k3s.dir.bin }}/k3s.sh"
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  when:
    - k3s.dir.data != defaults.dir.data
    - not ansible_check_mode

- name: Determine k3s bin target
  ansible.builtin.set_fact:
    # yamllint disable-line rule:line-length
    k3s_bin_target: "{{ '{{ k3s.dir.bin }}/k3s.sh' if k3s.dir.data != defaults.dir.data else '{{ k3s.dir.bin }}/k3s' | default('{{ k3s.dir.bin }}/k3s') }}"

- name: Create symlink'd commands (kubectl, crictl, ctr)
  ansible.builtin.file:
    src: "{{ k3s_bin_target }}"
    dest: "{{ k3s.dir.bin }}/{{ item }}"
    state: link
  with_items:
    - kubectl
    - crictl
    - ctr
  when: not ansible_check_mode

