---
################################################################################
# Create {{ k3s_cluster_config }} on ansible controller
#
- name: Create {{ k3s_cluster_config }} on ansible controller
  when: not ansible_check_mode
  run_once: true
  block:
    # Use a temporary file so that the node is marked 'changed' only when the
    # kubeconfig file is new or different.  See task "Copy kubeconfig file" below.

    - name: Create temporary file for kube config
      ansible.builtin.tempfile:
        state: file
      register: tempfile
      changed_when: false

    - name: Copy node kubeconfig to tempfile, {{ src }} to {{ dest }}
      vars:
        src: "/etc/rancher/k3s/k3s.yaml"
        dest: "{{ tempfile.path }}"
      ansible.builtin.copy:
        remote_src: true
        src: "{{ src }}"
        dest: "{{ dest }}"
        mode: "u=rw,g=,o="
      changed_when: false

    - name: Replace https://localhost:{{ api_port }} with https://{{ api_endpoint }}:{{ api_port }}
      ansible.builtin.command: >-
        {{ bin_dir }}/kubectl config set-cluster default
          --server=https://{{ api_endpoint }}:{{ api_port }}
          --kubeconfig {{ tempfile.path }}
      changed_when: false

    - name: Fetch {{ src }} to {{ dest }}
      vars:
        src: "{{ tempfile.path }}"
        dest: "{{ k3s_cluster_config }}"
      ansible.builtin.fetch:
        src: "{{ src }}"
        dest: "{{ dest }}"
        flat: true

    - name: Remove tempfile, {{ tempfile.path }}
      ansible.builtin.file:
        path: "{{ tempfile.path }}"
        state: absent
      changed_when: false


################################################################################
# Create ~{{ ansible_user }}/.kube/config on each host
#

- name: Setup ~{{ ansible_user }}/.kube/config
  when: not ansible_check_mode
  block:
    - name: Create local kube directory, {{ path }}
      vars:
        path: "~{{ ansible_user }}/.kube"
      ansible.builtin.file:
        path: "{{ path }}"
        state: directory
        owner: "{{ ansible_user }}"
        mode: "u=rwx,g=rx,o="

    - name: Copy {{ src }} to {{ dest }}
      vars:
        src: "{{ k3s_cluster_config }}"
        dest: "~{{ ansible_user }}/.kube/config"
      ansible.builtin.copy:
        src: "{{ src }}"
        dest: "{{ dest }}"
        owner: "{{ ansible_user }}"
        mode: "u=rw,g=,o="

