---

################################################################################
# Create {{ k3s_config_cluster }} on ansible controller
#
- name: Create kubeconfig on ansible controller, {{ k3s_config_cluster }}
  when: not ansible_check_mode
  run_once: true
  block:
    # Use a temporary file so that the node is marked 'changed' only when the
    # kubeconfig file is new or different.  See task "Copy kubeconfig file" below.

    - name: Create temporary file for kube config
      ansible.builtin.tempfile:
        state: file
      register: tempfile
      changed_when: false

    - name: Copy system kubeconfig, {{ str }}
      vars:
        src: "{{ etc_dir }}/{{ k3s_config_system }}"
        dest: "{{ tempfile.path }}"
        str: "{{ src }} --> {{ dest }}"
      ansible.builtin.copy:
        remote_src: true
        src: "{{ src }}"
        dest: "{{ dest }}"
        mode: "u=rw,g=,o="
      changed_when: false

    - name: Replace localhost cluster endpoint with {{ str }}
      vars:
        str: "{{ api_endpoint }}:{{ api_port }}"
      ansible.builtin.command: >-
        {{ bin_dir }}/kubectl config set-cluster default
          --server=https://{{ api_endpoint }}:{{ api_port }}
          --kubeconfig {{ tempfile.path }}
      changed_when: false

    - name: Fetch updated tempfile, {{ str }}
      vars:
        src: "{{ tempfile.path }}"
        dest: "{{ k3s_config_cluster }}"  # placed in playbook/
        str: "{{ src }} --> {{ dest }}"
      ansible.builtin.fetch:
        src: "{{ src }}"
        dest: "{{ dest }}"
        flat: true

    - name: Remove tempfile, {{ tempfile.path }}
      ansible.builtin.file:
        path: "{{ tempfile.path }}"
        state: absent
      changed_when: false

#########################################
# Create kubeconfig files on every server
#

- name: Create kubeconfig files on every server
  when: not ansible_check_mode
  block:
    - name: Create local kubeconfig directory, {{ path }}
      vars:
        path: "~{{ ansible_user }}/{{ k3s_config_userdir }}"
      ansible.builtin.file:
        path: "{{ path }}"
        state: directory
        owner: "{{ ansible_user }}"
        mode: "u=rwx,g=rx,o="

    - name: Copy cluster config, {{ str }}
      vars:
        src: "{{ k3s_config_cluster }}"
        dest: "~{{ ansible_user }}/{{ k3s_config_userdir }}/{{ k3s_config_cluster }}"
        str: "{{ src }} --> {{ dest }}"
      ansible.builtin.copy:
        src: "{{ src }}"
        dest: "{{ dest }}"
        owner: "{{ ansible_user }}"
        mode: "u=rw,g=,o="

    - name: Copy localhost config, {{ str }}
      vars:
        src: "{{ etc_dir }}/{{ k3s_config_system }}"
        dest: "~{{ ansible_user }}/{{ k3s_config_userdir }}/{{ k3s_config_local }}"
        str: "{{ src }} --> {{ dest }}"
      ansible.builtin.copy:
        remote_src: true
        src: "{{ src }}"
        dest: "{{ dest }}"
        owner: "{{ ansible_user }}"
        mode: "u=rw,g=,o="
