---

################################################################################
# Setup servers in cluster using k3s-init
#

- name: Initialize k3s HA embedded database, etcd
  include_role:
    name: "ha/etcd"
  when: ha_enabled

################################################################################
# Setup k3s service
#

- name: Copy K3s service file
  register: k3s_service
  ansible.builtin.template:
    src: "k3s-server.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Enable and check K3s service
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: "{{ true if k3s_service.changed else false }}"
    state: "{{ 'restarted' if k3s_service.changed else 'started' }}"
    enabled: true

- name: Perform node-token tasks
  ansible.builtin.include_tasks: "node-token.yml"

- name: Create ctl commands
  ansible.builtin.include_tasks: "ctl-commands.yml"

- name: Create kubeconfig
  ansible.builtin.include_tasks: "kube-config.yml"

##########################
# Set up HA cluster method

- name: Setup HA cluster method, {{ k3s_cluster_method | default('n/a') }}
  vars:
    role: "ha/{{ k3s_cluster_method }}"
  include_role:
    name: "{{ role }}"
  when:
    - ha_enabled
    - k3s_cluster_method != 'external'

######################################################################################
# Wait for control plane at {{ api_endpoint }}:{{ api_port }} before setting up agents
#

- name: Wait for control plane at {{ api_endpoint }}:{{ api_port }}
  wait_for:
    host: "{{ api_endpoint }}"
    port: "{{ api_port }}"
    timeout: 60

