---

################################################################################
# Setup servers in cluster using k3s-init
#

- name: Initialize k3s HA embedded database, etcd
  ansible.builtin.include_role:
    name: "ha_etcd"
  when: ha_enabled

################################################################################
# Setup k3s service
#

- name: Copy K3s service file
  register: k3s_service
  ansible.builtin.template:
    src: "k3s-server.service.j2"
    dest: "{{ k3s.dir.systemd }}/k3s.service"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Enable and check K3s service
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: "{{ true if k3s_service.changed else false }}"
    state: "{{ 'restarted' if k3s_service.changed else 'started' }}"
    enabled: true

- name: Perform node-token tasks
  ansible.builtin.include_tasks: "node-token.yml"

- name: Create ctl commands
  ansible.builtin.include_tasks: "ctl-commands.yml"

- name: Create kubeconfig
  ansible.builtin.include_tasks: "kube-config.yml"

##########################
# Set up HA cluster method

- name: Setup HA cluster method, {{ k3s.cluster.method | default('n/a') }}
  vars:
    role: "{{ reference.cluster.roles[k3s.cluster.method] }}"
  ansible.builtin.include_role:
    name: "{{ role }}"
  when:
    - ha_enabled
    - k3s.cluster.method != 'external'

#######################################################################
# Wait for control plane before setting up agents
#

- name: Wait for control plane at {{ str }}
  vars:
    str: "{{ k3s.cluster.address }}:{{ k3s.cluster.port }}"
  ansible.builtin.wait_for:
    host: "{{ k3s.cluster.address }}"
    port: "{{ k3s.cluster.port }}"
    timeout: 60
  run_once: true

