---
################################################################################
# node-token tasks
#

- name: Setup node-token
  block:
    - name: Wait for node-token
      ansible.builtin.wait_for:
        path: "{{ data_dir }}/server/node-token"

    - name: Read node-token from the server
      ansible.builtin.slurp:
        path: "{{ data_dir }}/server/node-token"
      register: node_token
      become: true

    - name: Store the server node-token
      ansible.builtin.set_fact:
        token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"

  when: not ansible_check_mode

- name: Setup dummy node-token
  ansible.builtin.set_fact:
    token: "ansible_check_mode token"
  when: ansible_check_mode

