---

- name: Remove downloaded k3s binary
  ansible.builtin.file:
    path: "{{ bin_dir }}/k3s"
    state: absent
  when: remove_packages | bool

#
# TODO: Where is k3s-selinux getting downloaded?
#       Are these tasks even necessary?
#
- name: Remove package k3s-selinux
  ansible.builtin.package:
    name: k3s-selinux
    state: absent
  when: remove_packages | bool

- name: Remove additional packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ install_additional_packages | default([]) }}"

- name: Remove yum repo files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/etc/yum.repos.d/rancher-k3s-common*.repo"
  when:
    - ansible_pkg_mgr == "yum"
    - remove_packages | bool

- name: Remove zypper repo files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/etc/zypp/repos.d/rancher-k3s-common*.repo"
  when:
    - ansible_pkg_mgr == "zypper"
    - remove_packages | bool

